
version: "3.7"
services:
  db:
    build:
      context: .
      dockerfile: pg-Dockerfile
    ports:
      - 5432:5432
    volumes:
      - data-volume:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
     image: "redis:alpine"
     ports:
       - "6379:6379"
     volumes:
       - ${PWD}/redis-data:/var/lib/redis
       - ${PWD}/redis.conf:/usr/local/etc/redis/redis.conf
     command: redis-server
  web-app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROJECT_DIR=${PROJECT_DIR}
    ports:
      - 8000:8000
    volumes:
      - ./:${PROJECT_DIR}
    env_file:
      - .env
    command: /bin/sh -c "chmod +x ${PROJECT_DIR}/entrypoint-webapp.sh &&
                         ${PROJECT_DIR}/entrypoint-webapp.sh"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "cd ${PROJECT_DIR}  && celery -A hoker_newz worker -l info"
    volumes:
      - ./:${PROJECT_DIR}
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: /bin/sh -c "cd ${PROJECT_DIR} && celery -A hoker_newz beat -l info"
    volumes:
      - ./:${PROJECT_DIR}
    depends_on:
      - db
      - redis
volumes:
  data-volume:
  redis-data:
